cljc_module('http',
            src = ['http.cljc',
                   'transport_client.cljs',
                   'transport_server.clj'],
            itests = 'http_test.cljc',
            modules = ['//lib/koh:environment',
                       '//ext:clj-http',
                       '//ext:org.clojure/data.json'])

cljc_module('http-p',
            itests = 'http_p_test.cljc',
            modules = [':http',
                       '//ext:funcool/promesa'])
