cljc_module('xml',
            src = ['xml.cljc',
                   'parser_client.cljs',
                   'parser_server.clj'],
            itests = 'xml_test.cljc',
            modules = ['//lib/koh:environment',
                       '//lib/koh:test',
                       '//ext:org.clojure/data.xml'])

cljc_module('xml-p',
            itests = 'xml_p_test.cljc',
            modules = [':xml',
                       '//ext:funcool/promesa'])
